version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10 
  pre_build:
    commands:
     -npm install cypress --save-dev
    - echo "install cypress dependencies..."
      - npm install
  build:
    commands:
      npm node_modules\.bin\cypress run
  post_build:
    commands:
      - echo "post_build step"