version: 0.2
env:
 variables:
  BUILD_DIR: "dist"
  S3_BUCKET: "aws-cypress-demo"
phases:
  install:    
    commands:
      - npm i
      - npm install cypress --save-dev
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - ./node_modules/.bin/cypress run -- spec DEMO/TableHandle.js
  post_build:
    commands:
      - echo "post_build step"