version: 0.2
env:
 variables:
  BUILD_DIR: "dist"
  S3_BUCKET: "aws-cypress-demo"
phases:
  install:    
    commands:
      - npm i
      - npm run build
      - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
      - npm start & npx wait-on http://127.0.0.1:8080
cache:
  paths:
    - node_modules/**/*
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/seperate-reports,overwrite=true,html=true,json=true,timestamp=mmddyyyy_HHMMss"' 
    finally:
      - npx mochawesome-merge "cypress/reports/seperate-reports/*.json" > mochawesome.json 
      - npx marge mochawesome.json 
      - mv mochawesome-report cypress/ 
      - ls -R cypress
  post_build:
    commands:
      - echo "post_build step" 
artifacts: 
  files: 
    - 'reports/**/*' 
    - 'screenshots/**/*' 
    - 'videos/**/*' 
    - 'mochawesome-report/**/*' 
  base-directory: 'cypress'
 