version: 0.2
env:
 variables:
  BUILD_DIR: "dist"
  S3_BUCKET: "aws-cypress-demo"
phases:
  install:    
    commands:
      - npm i
      - npm install cypress --save-dev
      - npm install wait-on
      - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
      - npm start & npx wait-on http://localhost:8080
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    finally:
      - npx mochawesome-merge@4 cypress/report/mochawesome-report/*.json > cypress/report/mochawesome.json
      - npx marge cypress/report/mochawesome.json
  post_build:
    commands:
      - echo "post_build step" 
artifacts:
  #base-directory: cypress
  #configFilePath: "**/mochawesome.json" 
  files: 
    - 'reports/**/*' 
    - 'screenshots/**/*' 
    - 'videos/**/*' 
    - 'mochawesome-report/**/*' 
  
 