version: 0.2
env:
 variables:
  BUILD_DIR: "dist"
  S3_BUCKET: "aws-cypress-demo"
phases:
  install:    
    commands:
      - npm i
      - npm i -D cypress @cypress/electron-plugin
      - npm uninstall cypress --save-dev
      - npm install cypress --save-dev
      - npm install mocha@8.2.1 mochawesome mochawesome-merge mochawesome-report-generator
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
       - ./node_modules/.bin/cypress run -- spec DEMO/TableHandle.js
    finally: 
      - npx mochawesome-merge "cypress/reports/seperate-reports/*.json" > mochawesome.json 
      - npx marge mochawesome.json 
      - mv mochawesome-report cypress/ 
      - ls -R cypress
  post_build:
    commands:
      - echo "post_build step" 
artifacts: 
  files: 
    - 'reports/**/*' 
    - 'screenshots/**/*' 
    - 'videos/**/*' 
    - 'mochawesome-report/**/*' 
  base-directory: 'cypress'
 