version: 0.2
phases:
  install:
    runtime-versions:
    nodejs: 12
    commands:
      npm install cypress --save-dev
  pre_build:
    commands:
    - echo "install cypress dependencies..."
      - npm install
  build:
    commands:
      npm node_modules\.bin\cypress run -- browser chrome
  post_build:
    commands:
      - echo "post_build step"