version: 0.2
phases:
  install:
  nodejs: 12
    commands:
      npm install -g @cypress/cli@6.2.1
  pre_build:
    commands:
    - echo "install cypress dependencies..."
      - npm install
  build:
    commands:
      cypress run test
  post_build:
    commands:
      - echo "post_build step"