version: 0.2
env:
 variables:
  BUILD_DIR: "dist"
  S3_BUCKET: "aws-cypress-demo"
phases:
 install:
  runtime-versions:
   nodejs: 12
  commands:
    - npm install
    -npm config set fund false --global  
pre-build:
  commands:
    - echo "install cypress dependencies..."  
build:
  commands:
   - pip3 install awscli --upgrade --user
   - aws s3 sync $BUILD_DIR s3://$S3_BUCKET --acl public-read
   - npm install cypress --save-dev
   - node_modules/.bin/cypress run --spec cypress/integration/DEMO/TableHandles.js 
post_build:
  commands:
   SUCCESS=$CODEBUILD_BUILD_SUCCEEDING node ./bin/notify.js