version: 0.2
phases:
  install:
    runtime-version:
    nodejs: 12
    commands:
     - echo "install cypress dependencies..."
      - npm install -g gatsby-cli
      - npm install -g purgecss
      - apt-get update
      - apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
  pre_build:
    commands:
   - echo "pre_build step"
  build:
    commands:
      - cd src
      - cd new-gatsby-blog
      - npm install
      - npm run-script build
      - node_modules/.bin/cypress run
  post_build:
    commands:
      - echo "post_build step"