version: 0.2
env:
 variables:
  BUILD_DIR: "dist"
  S3_BUCKET: "aws-cypress-demo"
phases:
  install:    
    commands:
      - npm i
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
       - export CONFIG="baseUrl=$CYPRESS_BASE_URL"
       - echo $CONFIG
       - NO_COLOR=1 ./node_modules/.bin/cypress run --browser chromium --headless --config "$CONFIG"
    finally: 
      - npx mochawesome-merge "cypress/reports/seperate-reports/*.json" > mochawesome.json 
      - npx marge mochawesome.json 
      - mv mochawesome-report cypress/ 
      - ls -R cypress
  post_build:
    commands:
      - echo "post_build step" 
artifacts: 
  files: 
    - 'reports/**/*' 
    - 'screenshots/**/*' 
    - 'videos/**/*' 
    - 'mochawesome-report/**/*' 
  base-directory: 'cypress'
 