version: 0.2
phases:
  install:
    run-as: user
    runtime-versions:
    nodejs: 10 
    commands:
      npm install cypress --save-dev
  pre_build:
    commands:
    - echo "install cypress dependencies..."
      - npm install
  build:
    commands:
      npm node_modules\.bin\cypress run
  post_build:
    commands:
      - echo "post_build step"