# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cypress CI and reporting

on:
  push:
    branches:
      -'main
  pull_request:
    branches:
      -'main'

jobs:
cypress-test:
  name: run on chrome 83
  runs-on: ubuntu-18.04
  container: cypress/browsers:node12.18.0-chrome83-ff77
    
  steps:
    - uses: actions/checkout@v2
      
      -name: install cypress and verify
       run:|
       npm ci
         $(npm bin)/cypress verify
       
    - name: run cypress tests
      run: npm run test:chrome
      continue-on-error: false
      
      -name: merge test case report
       
       run:| 
          mkdir public
         cp -r cypress/videos public/videos
         cp -r cypress/screeshots public/screenshots
         
     
       name:merge repo
       run:npm run combine:report
          
       -name:generate htlm report 
        run:npm run generate:report 
         
